### ISSUE TITLE
Re: "TODO randomize" payout of uneven pots, I don't think it should be random.

### ISSUE THREAD

**Issue by pastly** [pastly/cookerpoker#16]
https://github.com/pastly/cookerpoker/blob/1eb32f79ec986eab88267505d8ffcca613f0c31e/poker-server/src/endpoints/logic/game.rs#L314-317

I believe the thing card rooms do is pay the odd amount to the person in the earliest position.

**Comment by Deedasmi** [comment]
This is the current behavior. Just want to delete the TODO?
