### ISSUE TITLE
Discussion: Uneven Pots

### ISSUE THREAD

**Issue by Deedasmi** [pastly/cookerpoker#17]
Imagine the scenario:
1. Small blind forced to bet 5
2. Big blind forced to bet 10
3. Dealer bets 10
4. Small blind raises to 12. 
5. pot.finalize_round() is called.

The pot is not correct, and the hand should not be finalized. However, the pot currently accepts the uneven bet and will end up paying it out as if nothing were wrong. 

The parent table struct should be enforcing valid bets. This does mean that the pot itself is not 'safe' by itself. The main reason this was offloaded was that the pot cannot verify the pot is valid (all non-folded players in for the same amount) without knowing which players are folded. This requires knowledge of who is seated at the table, which the pot does not have and cannot currently access.

Couple options:
1. No change, pot is not 'safe' and behaves erratically when fed bad input. Table is responsible for validating the 'pot is right'. 
2. Panic on payout when notice that the final pot is not correct. Likely need to account for the last 'out' player folding, as they may have less in the pot than the winner. Not recommended. 
3. Force an overflow of the final pot to a max_in of the minimum value in the pot. In theory, any final pot with more than one person in it indicates one of three things:
  a. Two or more people in the final betting round came to the same bet. Overflow would have no effect.
  b. Someone won by being the last non-folded player, meaning they are the only one capable of winning the pot anyway. Overflow would have no effect.
  c. The player who overbet would have their overage moved to a side pot only they are in. This would still mean the pot was in a bad state, but the payout is settled to the lowest common denominator. 
4. finalize_hand() takes a list of players still capable of betting (fold removed, but also all_in removed as they will not have the same amount in the pot). All players who are in normal bet mode should have the same amount in the pot. 

There is currently two unit tests that test this behavior. `multi_winners` assumes that option 1 is taken, and the pot simply doesn't behave correctly. The pot currently awards the overbets to the winner of the hand, regardless of if the pot was not correct. `over_bet` the third option being implemented. These are mutually exclusive and no option should fix both tests. 

I'm leaning towards option 4, while being the least concrete, should cover the majority of cases this could cause an issue in an actual game. Can likely implement both 3 and 4.

**Comment by pastly** [comment]
Honestly I kinda like option 1. I've been reviewing the pot.rs code (still can't say I fully grok it) and where I'm at right now is the table should be responsible for making sure the pot is correct. And the pot should just do its best. If given garbage input, it's fine to give garbage output.

**Comment by pastly** [comment]
We've seemingly moved past needing this issue. We've gone with option 1: the pot code will do its best, but if you give it garbage, it will return garbage. Otherwise it behaves perfectly (so far ;p)
