### ISSUE TITLE
Feel free to not use X- prefix on HTTP headers

### ISSUE THREAD

**Issue by pastly** [pastly/cookerpoker#4]
IETF no longer recommends X- prefix on non-standard headers.

https://stackoverflow.com/a/3561399

**Comment by Deedasmi** [comment]
https://api.rocket.rs/v0.5-rc/rocket/request/trait.FromRequest.html

Code was shamelessy stolen

**Comment by pastly** [comment]
Moot anyway if/when we use cookies!
