### ISSUE TITLE
Re-think LogItem::PocketsDealt

### ISSUE THREAD

**Issue by Deedasmi** [pastly/cookerpoker#41]
This one variant doesn't seem to fall in line with the rest of them.

1. The HashMap, in all practical uses, will only ever have one entry when it is sent to client
2. LogItem will probably be logged, leaking the pocket to the DB/log file unless it's filtered there as well
3. The place where PocketsDelt actually is useful is the showdown, at which point the data is no longer sensitive. 

There a couple ways we could change this, in no particular order:

1. Getting pocket cards is a separate endpoint. This gives us easy fine-grain control, but breaks the flow of any future async client. 
2. Separate log entries for each player, and the filter just completely drops those that aren't for the correct player. 
3. Leave as is and just rename as 'ShowPocket(s)' or something along the lines of the more general usage.
4. ????. I feel like there is a better option, just not grasping it.

**Comment by pastly** [comment]
I propose this:

- `PocketsDealt(HashMap)` -> `PocketsDealt(Option<[Card; 2]>, Vec<PlayerId>)`. For the event log, the Option is None. When being sent to a player client, it is their pocket. The Vec in all cases is the players that were dealt pockets (or, if not PlayerId, then their seat index).
- GameInProgress keeps a HashMap with all pockets. When clients request an update on events and one of the new events is PocketsDealt, the GameInProgress fills in the Option with their pocket.

**Comment by pastly** [comment]
I further think you're probably right that the filters are a bit much and could be removed. In what I proposed above, they wouldn't even work.
