### ISSUE TITLE
The most basic of basic CSS

### ISSUE THREAD

**Issue by pastly** [pastly/cookerpoker#7]
I've used [mvp.css](https://andybrewer.github.io/mvp/) twice now (pastebin and blackjack site). I think we should grab it, change a couple colors, and use it at this point. Just so it looks significantly better, even if basic and bland still.

It should be dark (obviously :p), but if I pick this up, I should resist just copy/pasting the pastebin/bj version, thus having a 3rd site with the same color scheme.

**Comment by Deedasmi** [comment]
I'm good with more re-used CSS. Drop it in /static and we'll make an include block in the tera templates.

**Comment by Deedasmi** [comment]
Added the CSS and converted the templates, not sure how to force dark mode though?

**Comment by pastly** [comment]
What I did is edit the colors manually. And if there’s built in support for light/dark mode,  I deleted that (I don’t think there is, but something I worked in recently did, so maybe I’m misremembering). Everyone must see darkness!
